### ISSUE TITLE
hello omansak

### ISSUE THREAD

**Issue by HFAsif** [omansak/ASP.NET-CORE-MVC-Sample-Registration-Login-#1]
i have seen you have fixed youtube libvideo uri decription . can you fix it too in here https://github.com/flagbug/YoutubeExtractor . is possible ?

**Comment by HFAsif** [comment]
string jsUrl = string.Format("http://s.ytimg.com/yts/jsbin/player_ias-{0}.js", cipherVersion);

string functNamePattern = (@"\bc\s*&&\s*a\.set\([^,]+,\s*(?:encodeURIComponent\s*\()?\s*([\w$]+)\("); //Regex Formed To Find Word or DollarSign

var funcBody =
                Regex.Match(
                    js,
                    $@"(?!h\.){Regex.Escape(funcName)}=function\(\w+\)\{{(.*?)\}}",
                    RegexOptions.Singleline).Value;

it not works in 
foreach (var line in lines.Skip(1).Take(lines.Length - 2)) 

can you fix it too

**Comment by omansak** [comment]
@developerss it is not fork of libvideo. Please open the right location

**Comment by HFAsif** [comment]
i have posted can you see please 
https://github.com/flagbug/YoutubeExtractor/issues/358
